// AUTO-GENERATED by tools/gen-go-types.py — DO NOT EDIT
// Source: rust/core/fields.yaml

package seedfaker

import (
	"strconv"
	"strings"
)

// Opts — field-level options. Zero values = not set.
type Opts struct {
	N      int    // Number of values (0 or 1 = single value)
	Omit   int    // Omit percentage (0 = no omit)
	Range  [2]int // [from, to]; both 0 = no range
	Length int    // For length-capable fields (digits, hex, etc.)
	Upper  bool
	Lower  bool
	Asc    bool
	Desc   bool
	Xuniq  bool
	Sign bool
	Byte bool
	Hex bool
	Rgb bool
	Rgba bool
	Plain bool
	Unix bool
	Ms bool
	Log bool
	Us bool
	Eu bool
	E164 bool
	Intl bool
	Alpha3 bool
	Numeric bool
	Short bool
	Underscore bool
	Space bool
	Dash bool
	Dot bool
	Comma bool
	Usd bool
	Eur bool
	Gbp bool
	Crypto bool
	Pin bool
	Memorable bool
	Mixed bool
	Strong bool
	International bool
	Internal bool
	Http bool
	Https bool
	Ftp bool
	Ws bool
	Wss bool
	Ssh bool
	System bool
	Registered bool
	Dynamic bool
	Unprivileged bool
	Service bool
	Fast bool
	Slow bool
	Seconds bool
	Ratio1X1 bool
	Ratio4X3 bool
	Ratio3X2 bool
	Ratio16X9 bool
	Ratio21X9 bool
	Ratio9X16 bool
	Ratio3X4 bool
	Ratio2X3 bool
	Btc bool
	Multi bool
}

func buildSpec(name string, opts Opts) string {
	parts := []string{name}

	// Field-specific modifiers (generated from fields.yaml)
	for _, pair := range []struct {
		flag bool
		key  string
	}{
		{opts.Sign, "sign"},
		{opts.Byte, "byte"},
		{opts.Hex, "hex"},
		{opts.Rgb, "rgb"},
		{opts.Rgba, "rgba"},
		{opts.Plain, "plain"},
		{opts.Unix, "unix"},
		{opts.Ms, "ms"},
		{opts.Log, "log"},
		{opts.Us, "us"},
		{opts.Eu, "eu"},
		{opts.E164, "e164"},
		{opts.Intl, "intl"},
		{opts.Alpha3, "alpha3"},
		{opts.Numeric, "numeric"},
		{opts.Short, "short"},
		{opts.Underscore, "underscore"},
		{opts.Space, "space"},
		{opts.Dash, "dash"},
		{opts.Dot, "dot"},
		{opts.Comma, "comma"},
		{opts.Usd, "usd"},
		{opts.Eur, "eur"},
		{opts.Gbp, "gbp"},
		{opts.Crypto, "crypto"},
		{opts.Pin, "pin"},
		{opts.Memorable, "memorable"},
		{opts.Mixed, "mixed"},
		{opts.Strong, "strong"},
		{opts.International, "international"},
		{opts.Internal, "internal"},
		{opts.Http, "http"},
		{opts.Https, "https"},
		{opts.Ftp, "ftp"},
		{opts.Ws, "ws"},
		{opts.Wss, "wss"},
		{opts.Ssh, "ssh"},
		{opts.System, "system"},
		{opts.Registered, "registered"},
		{opts.Dynamic, "dynamic"},
		{opts.Unprivileged, "unprivileged"},
		{opts.Service, "service"},
		{opts.Fast, "fast"},
		{opts.Slow, "slow"},
		{opts.Seconds, "seconds"},
		{opts.Ratio1X1, "1x1"},
		{opts.Ratio4X3, "4x3"},
		{opts.Ratio3X2, "3x2"},
		{opts.Ratio16X9, "16x9"},
		{opts.Ratio21X9, "21x9"},
		{opts.Ratio9X16, "9x16"},
		{opts.Ratio3X4, "3x4"},
		{opts.Ratio2X3, "2x3"},
		{opts.Btc, "btc"},
		{opts.Multi, "multi"},
		{opts.Upper, "upper"},
		{opts.Lower, "lower"},
		{opts.Xuniq, "xuniq"},
		{opts.Asc, "asc"},
		{opts.Desc, "desc"},
	} {
		if pair.flag {
			parts = append(parts, pair.key)
		}
	}

	if opts.Length > 0 {
		parts = append(parts, strconv.Itoa(opts.Length))
	}
	if opts.Omit > 0 {
		parts = append(parts, "omit="+strconv.Itoa(opts.Omit))
	}
	if opts.Range[0] != 0 || opts.Range[1] != 0 {
		parts = append(parts, strconv.Itoa(opts.Range[0])+".."+strconv.Itoa(opts.Range[1]))
	}

	return strings.Join(parts, ":")
}
